Import('env')

env.InstallPerl(['salign.pm', 'salign/CGI_Utils.pm', 'salign/Utils.pm',
                 'salign/index_page.pm', 'salign/submit_page.pm',
                 'salign/results_page.pm', 'salign/chimera.pm'])
